Add apertis
repology/repology-updater pull request #1097
Opened 2020-11-24 18:35 UTC by jjardon

2020-11-24 19:41 UTC, AMDmi3 requested changes

2020-11-24 19:41 UTC, AMDmi3 commented on repos.d/deb/apertis.yaml
> +  desc: Trisquel 2020
Please use correct distro name here, `v` prefix as well if it's reasonable.

2020-11-24 19:41 UTC, AMDmi3 commented on repos.d/deb/apertis.yaml
> +- name: apertis_2020
Shouldn't it be `v2020`? Looks like version is mentioned with `v` on the site.

2020-11-24 19:41 UTC, AMDmi3 commented on repos.d/deb/apertis.yaml
> +    - name: [ v2020/development, v2020/target, v2020/sdk v2020/hmi, v2020-updates/development, v2020-updates/target, v2020-updates/sdk, v2020-updates/hmi ]
Comma missing between sdk and hmi

2020-11-24 19:41 UTC, AMDmi3 commented on repos.d/deb/apertis.yaml
> +    - name: [ v2021dev3/development, v2021dev3/target, v2021dev3/sdk v2021dev3/hmi ]
Comma missing here as well

2020-11-24 19:41 UTC, AMDmi3 commented on repos.d/deb/apertis.yaml
> +  color: '669fdd'
May use `3a5a80` here is it's the color used for the logo on the site.

2020-11-24 19:41 UTC, AMDmi3 commented on repos.d/deb/apertis.yaml
> +  minpackages: 20000
The repo doesn't have 20k packages, so this should be around 3500.

2020-11-24 19:41 UTC, AMDmi3 commented on repos.d/deb/apertis.yaml
> +- name: apertis_2021
Same changes as with 2020 repo are needed here.

2020-11-24 19:48 UTC, jjardon commented
@AMDmi3 Thanks for the quick review and sorry for all the little mistakes; I think everything is ok now

2020-11-25 16:28 UTC, merged

2020-11-25 18:46 UTC, AMDmi3 commented
Deployed, thanks!